#!/bin/bash
# Regenerate the per-harness contract templates:
#   shared/contract-core.md + <harness>/models-block.md  ->  claude/CLAUDE.md, kimi/AGENTS.md.template
# The contract core is single-source; only the dated models blocks differ per harness.
# Run after editing either source. CI (test.yml) fails if the generated files are stale.
set -euo pipefail
cd "$(dirname "$0")/.."

build() { # <harness-dir> <instruction-file-name> <header-comment> <output>
  local harness="$1" ifile="$2" header="$3" out="$4"
  {
    printf '%s\n' "$header"
    awk -v block="$harness/models-block.md" '
      /^\{\{MODELS_BLOCK\}\}$/ { while ((getline line < block) > 0) print line; next }
      { print }
    ' shared/contract-core.md | sed "s/{{INSTRUCTION_FILE}}/$ifile/g"
  } > "$out"
  echo "wrote $out"
}

build claude CLAUDE.md \
  '<!-- → copy to ~/.claude/CLAUDE.md (merge if one exists). Fill ALL {{placeholders}} — 3 working-style, 4 in the dated block. Current model names: code.claude.com/docs/en/model-config. GENERATED by scripts/sync-contract.sh — edit shared/contract-core.md or claude/models-block.md, not this file. -->' \
  claude/CLAUDE.md

build kimi AGENTS.md \
  '<!-- → copy to ~/.kimi-code/AGENTS.md (merge if one exists). Fill ALL {{placeholders}} — 3 working-style, 1 date. Model aliases live in your config.toml [models.*] entries. GENERATED by scripts/sync-contract.sh — edit shared/contract-core.md or kimi/models-block.md, not this file. -->' \
  kimi/AGENTS.md.template
